version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: '0.0.0.0'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'testeando'
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_HOST: '0.0.0.0'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testeando
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:33060"
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: ./app
    ports:
      - "5173"
