version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "5173:5173"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: testeando
    networks:
      back-tier:
        ipv4_address: "172.23.0.4"
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: testeando
      MYSQL_PASSWORD: '123456'
    volumes:
      - db:/var/lib/mysql
      - ./data/test.sql:/docker-entrypoint-initdb.d/test.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      back-tier:
        ipv4_address: "172.23.0.2"
volumes:
  db:
    driver: local
networks:
  back-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"